### ISSUE TITLE
Draft and send message to interested groups.

### ISSUE THREAD

**Issue by kristiholmes** [data2health/architecting_attribution#22]

**Comment by jmcmurry** [comment]
If you haven't already, please make sure to reach out to the PIs that already expressed interest in the project. Select your project from the dropdown [here](https://docs.google.com/spreadsheets/d/1PR6jLSz3KedD9bEWQcFr-LJRQfkXo_GcFOHXZMOgd7o/edit#gid=0).

**Comment by jmcmurry** [comment]
ps. This just in: a coordinated email will be going out for all projects; stay tuned.

**Comment by kristiholmes** [comment]
hi - I would like to send this email out directly to welcome people to the project.  I think it provides a nice opportunity to introduce them to the work and team and get them integrated with program resources.  Perhaps we can identify key items you would like to include in such an email and then those of us who want to engage can do so? @mellybelly @jmcmurry @firaswehbe @LisaOKeefe1

**Comment by LisaOKeefe1** [comment]
Hi @kristiholmes and thanks!  Who do you see your audience being? Will they contribute code or make other contributions? This will help me to share what I think might be most helpful!

**Comment by kristiholmes** [comment]
hi @LisaOKeefe1 - thanks for your question.  I think the overall audience will be fairly diverse, from a wide range of stakeholder domains.  I think they could contribute in big and small ways - and all of it important. Some ideas include requirements gathering, feature requests, testing, feedback on the data models, collaboration on demonstrators, etc. Thanks for your ideas :)

**Comment by jmcmurry** [comment]
I'm waiting for feedback [on my draft](https://docs.google.com/document/d/1yQdVRBZFg8X-WrofolvGhNHMVTdDcxjPYlyjhAPCyoY/edit) for all recipients as a baseline from which specific emails could be sent about specific projects.

**Comment by LisaOKeefe1** [comment]
@kristiholmes, Some things I suggest including in this message to help people feel welcome and to lessen their anxiety about being part of a new community (or somewhere else if more appropriate):

- **Joining the community** - quick thanks and overview explaining how to onboard

- **All skills are welcome** - here is where we say something like, "You don't have to be a programmer to contribute! Here are some of our needs: _____________"

- **How to make your first contributions**. Here's where we provide some resources like a hands-on github tutorial

- **Share how rewarding this can be (lessen barrier to entry)**. One organization did this cool thing where they asked people on twitter to share how they felt about their first open source commits. They shared the link to those responses in the welcome message. 

Also related to lessening the barrier to entry, fear in contributing, I recommend marking a First-timers-only label to certain tasks. This makes a statement that new people are welcome, valued and gives an easy way for them to start the project. In the software world, it's often said the hardest part about getting into open source is figuring out where you can contribute. 

This label often comes with a statement from the project owner that says "I"m here to help you make your first commit. This issue is rather a bit easier than normal. Anyone who's already contributed to the project is not allowed to touch this one! It's for you!" 

Please let me know if you have questions.  Thanks!

**Comment by jmcmurry** [comment]
Baseline email was sent; all ok to proceed with project - specific communications.

**Comment by LisaOKeefe1** [comment]
Not sure if we can close this. The original task has been completed but the process of outreach to interested parties and groups is ongoing. @kristiholmes ?

**Comment by kristiholmes** [comment]
Great point.  I think we can close since this general email went out from cd2h, but perhaps we start a new issue for the specific things we do from this point forward?

@LisaOKeefe1

**Comment by jmcmurry** [comment]
That's great! Related reminders:

# Project email addresses
You can **view/copy email addresses for all onboarded participants for your project** here on the [cd2h-people-slim](bit.ly/cd2h-people-slim) (The doc is shared with only those who have onboarded; feel free to reference that doc but please refrain from posting email addresses in GitHub as a) the repos are public and addresses can be bot-scraped, b) there's a risk of getting out of sync with the source of truth.

# Keeping communications current
[cd2h-people-slim](bit.ly/cd2h-people-slim) contains a tab for newcomers so you can reach out to people that may have onboarded after your last round of communications went out.
