### ISSUE TITLE
Spot check Nicole's mapping of COAR-wikidata mappings

### ISSUE THREAD

**Issue by LisaOKeefe1** [data2health/architecting_attribution#43]
Related to issue #38 
https://docs.google.com/spreadsheets/d/1Mw8gK2NUGM8po7GGRtJTShRM2QNFoR19VJrjQuVCDW8/edit#gid=323661248)

Nicole needs this in order to move on. 

If anyone in the community would like to comment on these, please do!

**Comment by marijane** [comment]
All mappings have been checked, and skos relationships added.  i think these are ready to add to wikidata!

we do still need to decide what to do with the concepts that aren't found in wikidata at all.  some of them are what i would call "abstract" concepts that mostly serve to group concepts in COAR, but some of them we might want to figure out how to add as new concepts in wikidata.

**Comment by kristiholmes** [comment]
hi @nicolevasilevsky @marijane  @LisaOKeefe1 - It turns out that our team at Galter has been working on resource object types. :)  Given the amount of thought and time given to this, I would like to touch base before we submit to wikidata - ok w everyone? Info below, let me know what you think. Thanks!

**Resource Types with hierarchy and UI label:** https://docs.google.com/spreadsheets/d/101zDjXZkQrot97YPG5HKmxRrsFp6J-VHUujK0YD91fQ/edit?usp=sharing

from @saragon02 about this list:
>The source in an amalgamation of existing DH resource types against the COAR resource type vocab. Our end result is a homegrown hierarchy of resource type terms that can be stored as a hierarchy and added to later. I plan to write up the final version in a Google Doc and share it prior to the integration of resource types in our next sprint.

>In addition, the amalgamation I mentioned above was reached through our meetings with the DIWG Metadata Subcommittee. We spent a good amount of time discussing the applicability and general useability of a variety of MeSH-based and other resource types.

Would be great to touch base about this - would be helpful to see what have been done so far and can be applied here, as there is a lot of overlap.  Likewise, is there anything missing? Would be good to touch base when folks have time. thanks
